apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: viberater-frontend
  namespace: viberater
  labels:
    app: viberater-frontend
spec:
  host: viberater.apps.homeserv.merrett.lan
  to:
    kind: Service
    name: viberater-frontend-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
